version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
  build:
    commands:
      - echo "Building Go binary..."
      - GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap main.go
  
  post_build:
    commands:
      - echo "Zipping artifact..."
      - chmod +x bootstrap
      - zip function.zip bootstrap
      - echo "Build completed on `date`"
artifacts:
  files:
    - function.zip